// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADoUem7PCXnthnEz47zBbpN33aGhZQuxA',
    appId: '1:160456497546:web:943fbcda42bce5dc5c5073',
    messagingSenderId: '160456497546',
    projectId: 'chatspan',
    authDomain: 'chatspan.firebaseapp.com',
    storageBucket: 'chatspan.appspot.com',
    measurementId: 'G-7MZ9W6CHTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNBSLvW7TzC03efAdy9EkJREKoja8TkEo',
    appId: '1:160456497546:android:b6d3df1543a2d0d35c5073',
    messagingSenderId: '160456497546',
    projectId: 'chatspan',
    storageBucket: 'chatspan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1DF7NsivTSy1_EbDePogbyf9AH5hhV1s',
    appId: '1:160456497546:ios:94284ec80691a2fb5c5073',
    messagingSenderId: '160456497546',
    projectId: 'chatspan',
    storageBucket: 'chatspan.appspot.com',
    iosClientId: '160456497546-ls3303s8h63uarku7h80eui3d83hu1a7.apps.googleusercontent.com',
    iosBundleId: 'com.7span.chatApp',
  );
}
